#!/bin/bash

usage=$(awk '{u=$2+$4; t=$2+$4+$5; if (NR==1){u1=u; t1=t;} else {result = ($2+$4-u1) * 100 / (t-t1); if (result > 10) printf "%.0f%%", result; else printf "%.1f%%", result;}}' <(grep 'cpu ' /proc/stat) <(sleep 1;grep 'cpu ' /proc/stat))

echo 💻"$usage"
