#!/bin/sh
#Stolen from Winny https://blog.winny.tech/posts/toggle-redshift-with-keyboard-shortcut/
set -eu
if ! pkill -x -SIGUSR1 redshift; then
    echo 'Could not find redshift process to toggle.' >&2
    exit 1
fi
