#!/bin/bash

case "$BLOCK_BUTTON" in
    1) #st -t stfloat -g 100x15+500 -e curl wttr.in/Norwich?format=3;; 
esac

#curl wttr.in/Norwich?format=3 | awk '{print $NF}'

#curl wttr.in/Norwich?format=3 | awk '{print $NF}'
var=$(curl wttr.in/Norwich?format=3 | awk '{print $NF}')
echo "🌥️"$var""
